### PR TITLE
Improved Reliability for OrderBook and AuthenticatedClient

### PR DESCRIPTION
**Pull request by PaulMest**
* Addressed failures in `OrderBook.change()` under certain conditions.
* Use `raise_for_status()` to get clearer errors when GDAX is unavailable

### CODE REVIEW

**Comment by bryankaplan** [comment]
Please see the discussion about error handling in #27. I plan to refactor our `requests` usage to surface API errors and network errors, and to eliminate all of the redundancy around our network calls. I'm waiting for #64 to be implemented before moving forward with that.

I do not believe all of these `raise_for_status()`s are a good long-term solution, though they're obviously useful until we have something better that's ready to ship.

**Comment by PaulMest** [comment]
Just so I'm clear on "they're obviously useful until we have something better".

Does this mean:
1) You'd approve this PR, but the `raise_for_status` code will be removed in the future?
2) You'd like me to comment out those lines and re-submit the PR?
3) Something else?

My vote would be for 1 since `raise_for_status` has been super helpful in diagnosing the problems with GDAX over the last week.

**Comment by bryankaplan** [comment]
I'm sorry for being ambiguous. I meant option 1. I wrote the comment mainly to provide some context for @danpaquin to consider when he decides if he wants to approve this. Yes, I think it's helpful, and yet I also want to replace it eventually.

**Comment by PaulMest** [comment]
Great. Thanks for the comments. I'll wait for more comments from @danpaquin when he has some time to review.

**Comment by PaulMest** [comment]
I've actually figured out a better way to DRY up the OrderBook. I'll submit a new PR when it's ready.

**Comment by bryankaplan** [comment]
Please consider #64 when refactoring that.

**Comment by danpaquin** [comment]
I quickly want to comment on the raise_for_status() changes.  Error handling requires more thought.  It will return a vanilla error without the description from the API.  It has been commented out to remind myself to reconsider how to handle API errors.  Our conversation around this has been fragmented to this point, but I have been experimenting. I will create a topic once I formulate some ideas.

**Pull request closed without merging**
