### PR TITLE
minor change to allow channels

### PR DESCRIPTION
**Pull request by lirenz**
Added a minor change to allow channel messages in the websocket client. I found the L2 + ticker feeds to be much more useful than the full feed (because of potential for lost and/or out of sequence messages) when syncing an orderbook.

### CODE REVIEW

**Comment by koelscha** [comment]
Very good idea. However, I think `message_type` is the parameter that should be used for that

**Comment by jeremyjordan** [comment]
@koelscha the [official GDAX API](https://docs.gdax.com/#channels) refers to them as channels

**Comment by jeremyjordan** [comment]
I disagree. 

To quote the GDAX API documentation, "To begin receiving feed messages, you must first send a subscribe message to the server indicating which channels and products to receive."

In this request, the `message_type` will be `"subscribe"` and the desired channels and products may be specified by the `product_ids` and `channels` attributes.

**Comment by lirenz** [comment]
You subscribe to channels, not message_types. We're not filtering message_types, each channel provides pretty unique content.

I'm thinking of pushing a L2 order book (in case people are interested). It'll be faster / potentially more accurate, but less granular (in case you care about individual orders + placements).

**Comment by jeremyjordan** [comment]
@lirenz An L2 order book would be great, especially if you could connect it to a PyMongo client.

**Comment by koelscha** [comment]
You are right, in the gdax documentation, this is what they say. The code here uses heartbeat as message type though, which is clearly a channel. So, what I was suggesting is either using the message type in this code or replacing it by channels. The latter does make more sense as it is consistent with the api docs

**Comment by danpaquin** [comment]
This conflict was my fault merging a higher priority PR.  Please resolve and I'll merge next.

**Pull request closed without merging**
