### PR TITLE
log incoming orderbook data to the console

### PR DESCRIPTION
**Pull request by cyzanfar**
added a `printMessage` method that the `message` returned from the websocket and logs it to the console.

Let me know what you think 💯

### CODE REVIEW

**Comment by danpaquin** [comment]
Hey @cyzanfar, while this is a great implementation, I am hesitant to commit changes that include unnecessary functions, such as printMessage(). Please move this logic into the "__main__" method so that the skeleton of the class ispreserved. Let me know if this doesn't make sense!

**Comment by cyzanfar** [comment]
That makes total sense! Will update it now.

**Comment by danpaquin** [comment]
Im on mobile so I am unable to edit messages. Please add your changes into a class that inherits OrderBook that we can use in the documentation as an example. Please see the websocket.py for something similar in the '__ main__' function.

**Comment by cyzanfar** [comment]
you got it ;)

**Comment by cyzanfar** [comment]
Sure thing. Let me update that :)

**Comment by cyzanfar** [comment]
I'm a bit confused. In the `WebsocketClient.py` `onOpen` in overwritten in the `myWebsocketClient` object. How is that different from the `WebsocketOrderBook` object I wrote ?

**Pull request closed without merging**
