### PR TITLE
update readme to camelcase

### PR DESCRIPTION
**Pull request by jbrower95**

### CODE REVIEW

**Comment by Jigsaw-Jams** [comment]
Hey @jbrower95 it's funny you submitted this as we recently just changed from the old camelCase naming (in both documentation and code) to the Pythonic convention of using all lowercase separated by underscores. This was a recent change to make the package more Pythonic and conform to PEP-8 conventions 😄  

See #37

**Comment by danpaquin** [comment]
Thank you for submitting! I apologize for the interim where we had Non backwards compatible code pushed to our repo.  The current master branch has been pushed to PyPI so the PEP 8 guidelines are satisfied where we no longer you camel case for method names.

**Comment by jbrower95** [comment]
Whoops! Yeah the version I installed from pip still had camel-cased names so I tried to get this PR out quickly. Is there any way to install a more up to date version with pip?

Thanks

**Comment by danpaquin** [comment]
Sure!

'pip install gdax --upgrade'

**Pull request closed without merging**
