### PR TITLE
PEP 8 formatting and Pythonic conventions

### PR DESCRIPTION
**Pull request by acontry**
Supersedes PR #52 (I got burned from developing on master on my fork and learned a good lesson).

@danpaquin let me know if there's anything else you'd like to see in this specific PR. Of course these changes break any backwards compatibility but it will be good in the long run 😃

### CODE REVIEW

**Comment by Jigsaw-Jams** [comment]
Could we merge this? 😃  I want to make a few changes, but don't want to work with all the old method names and definitions.

**Comment by danpaquin** [comment]
Sure! Im trusting you here since I won't be able to manually test for another 10 hours.

**Comment by acontry** [comment]
Thanks! Yes, unit tests would be valuable to add soon to ensure everything still works as we make changes 😀

**Comment by danpaquin** [comment]
Now that we comply to standards, it will surely help development in the long run.

**Comment by danpaquin** [comment]
Additionally, I'll be updating the readme doc as it's now out of date.

**Comment by acontry** [comment]
I did update the readme to jive with the changes but could have missed something.

**Comment by danpaquin** [comment]
Oops, I'm on mobile and scrolled by those changes. Thank you for the thorough work!

**Comment by Jigsaw-Jams** [comment]
I ran through some manual tests for everything in the public client, and a majority of methods in the authenticated client and everything seems to be working well there.

**Comment by bryankaplan** [comment]
@acontry Thank you! This is a great PR.

**Pull request merged**
